num1 = int(input("input first number : "))
num2 = int(input("input second number : "))
print(num1,"+",num2,"=",(num1+num2))
print(num1,"-",num2,"=",(num1-num2))
print(num1,"*",num2,"=",(num1*num2))
print(num1,"/",num2,"=",(num1/num2))